name: keepalive-shinyapps

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (heure UTC)
  workflow_dispatch:        # lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le secret
        run: |
          if [ -z "${{ secrets.SHINYAPP_URL }}" ]; then
            echo "Secret SHINYAPP_URL manquant (Settings > Secrets and variables > Actions)."
            exit 1
          fi

      - name: Réveiller l'application
        shell: bash
        run: |
          URL="${{ secrets.SHINYAPP_URL }}"
          echo "Ping vers: $URL"
          for i in {1..5}; do
            CODE=$(curl -L -sS -o /dev/null -w "%{http_code}" --max-time 25 \
              "$URL/?_keepalive=$(date +%s)")
            echo "Essai $i: HTTP $CODE"
            case "$CODE" in
              200|301|302|303|307|308) exit 0 ;;
            esac
            sleep $((i*2))
          done
          echo "Échec de réveil après 5 tentatives."
          exit 1
